### ISSUE TITLE
Crash at run

### ISSUE THREAD

**Issue by balwierz** [genotoul-bioinfo/dgenies#10]
**Describe the bug**
Crash at start

**To Reproduce**
`dgenies run`

**Expected behavior**
no crash

**Screenshots**
```
$ dgenies run
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
Traceback (most recent call last):
  File "/usr/local/bin/dgenies", line 341, in <module>
    run(*args)
  File "/usr/local/bin/dgenies", line 171, in run
    app = launch(mode=mode, debug=debug)
  File "/usr/local/lib/python3.7/dist-packages/dgenies/__init__.py", line 40, in launch
    UPLOAD_FOLDER = config_reader.upload_folder
AttributeError: 'AppConfigReader' object has no attribute 'upload_folder'
```

**Computer (please complete the following information):**
Debian Buster.
Python 3.7.3
Installed via pip3 as root

**Comment by chklopp** [comment]
Can you attach your configuration file (application.properties) found in you install folder?

**Comment by chklopp** [comment]
You can also check the configuration section at 
http://dgenies.toulouse.inra.fr/install

**Comment by balwierz** [comment]
```
$ cat /usr/local/lib/python3.7/dist-packages/etc/dgenies/application.properties
[global]
config_dir = ###USER###/.dgenies
upload_folder = /tmp/dgenies
data_folder = ###CONFIG###/data

# batch system type: local, sge, slurm
batch_system_type = local

web_url = http://localhost:5000

# Max size of uploaded files (also for files from URL, size uncompressed):
# Please set the unit: M for Megabyte or G for Gigabyte (-1 without unit to don't set a limit)
max_upload_size = 3G
# Max upload file size for all-vs-all (only target):
# Please set the unit: M for Megabyte or G for Gigabyte (-1 without unit to don't set a limit)
max_upload_size_ava = 1G
# Max upload file size (compressed or not, only for uploaded files, not from URL):
# Please set the unit: M for Megabyte or G for Gigabyte (-1 without unit to don't set a limit)
max_upload_file_size = 1G


[debug]
# Debug (enable only for tests)
enable = False
log_dir = ###CONFIG###/logs
# List of allowed IPs for tests, comma separated:
allowed_ip_tests =


[cluster]
drmaa_lib_path = ###SET_IT###
#Native specs: options passed to the scheduler
### Slurm: --mem-per-cpu={0} --ntasks={1} --time={2}
### SGE: -l mem={0},h_vmem={0} -pe parallel_smp {1}
### Note: copy&paste specifications for your scheduler. You can customize it.
### Always use {0} for memory, {1} for number of CPUs ({2} for duration time if slurm). All are required.
### If you don't want to change anything, don't edit anything.
native_specs = ###DEFAULT###

# If batch_system_type is not local, small jobs can be still run locally.
# Set to 0 to run all jobs on the cluster
max_run_local = 10
max_wait_local = 5

# To run only big jobs on the cluster, set the min query and target size (if max_run_local is reached, these parameters are ignores):
# Default parameters is for jobs that runs in approx. more than 3-4 minutes and consume approx. more than 9 GO of RAM
# Please set the unit: M for Megabyte or G for Gigabyte
min_query_size = 500M
min_target_size = 700M

prepare_script = ###PROGRAM###/bin/all_prepare.py
python3_exec = python3
# Max memory:
memory = 32
# Max memory for all-vs-all mode:
memory_ava = 32


[database]
type = sqlite
url = ###USER###/.dgenies/database.sqlite
# Not used for sqlite:
port = 3306
db =
user =
password =


[mail]
status = mail@dgenies
reply = mail@dgenies
org = "Dgenies team"
send_mail_status = True


[cron]
### Menage
# Time to launch the cron:
clean_time = 1h00
# Frequency (days):
clean_freq = 1


[jobs]
# Number of parallel runs for local jobs:
run_local = 1
data_prepare = 2
max_concurrent_dl = 5

[example]
query =
target =

[analytics]
enable_logging_runs = False
```

**Comment by florealcab** [comment]
Which command do you run exactly to install it? The location of your application.properties seems to be incorrect. Maybe it's because of your installation command, or it's a bug.

**Comment by balwierz** [comment]
I did `sudo pip3 install dgenies`.

Deps got pulled and installed 
`Flask-Mail-0.9.1 Jinja2-2.9.6 Markdown-2.6.11 Werkzeug-0.15.4 argparse-1.4.0 biopython-1.70 blinker-1.4 dgenies-1.2.0.1 drmaa-0.7.9 flask-0.12.4 intervaltree-2.1.0 itsdangerous-1.1.0 matplotlib-2.1.2 pbr-5.3.1 peewee-2.10.2 psutil-5.4.8 python-crontab-2.2.8 pyyaml-3.12 requests-2.18.4 tendo-0.2.15 urllib3-1.22`

**Comment by florealcab** [comment]
This is a good command line. So it seems that the install does not install config at the good place. Maybe it's due to the version of pip you have. I'll inverstigate it.

Anyway, you can make it working now. Please create this folder: /etc/dgenies (as root). Then, copy the application.properties inside it. Now, it should work properly.

**Comment by balwierz** [comment]
It did work. I was able to run dgenies. However, when I click 'run' in the browser I am getting an error:


`Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

In the console the error is

`File "/usr/local/lib/python3.7/dist-packages/dgenies/tools.py", line 127, in load_yaml
    raise FileNotFoundError("ERROR: tools.yaml not found.")`

**Comment by florealcab** [comment]
Indeed, the tools.yaml is also at the wrong place. Please copy all files present in /usr/local/lib/python3.7/dist-packages/etc/dgenies into the /etc/dgenies folder you created.

**Comment by balwierz** [comment]
Seems to work, thanks!

```
pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
```
