### ISSUE TITLE
Dgenies fails with flask 3

### ISSUE THREAD

**Issue by pbordron** [genotoul-bioinfo/dgenies#98]
Dgenies fails with flask 3

**Installation**
```
conda create -c conda-forge -c bioconda -n dgenies dgenies
```

**Run**
```
conda activate dgenies
dgenies run
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/dgenies/bin/dgenies", line 384, in <module>
    run(*args)
  File "/home/user/miniconda3/envs/dgenies/bin/dgenies", line 202, in run
    app = launch(mode=mode, tools_config=tools_config, flask_config=flask_config, debug=debug)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/dgenies/lib/python3.12/site-packages/dgenies/__init__.py", line 116, in launch
    from dgenies import views
  File "/home/user/miniconda3/envs/dgenies/lib/python3.12/site-packages/dgenies/views.py", line 13, in <module>
    from flask import render_template, request, url_for, jsonify, Response, abort, send_file, send_from_directory, Markup
ImportError: cannot import name 'Markup' from 'flask' (/home/user/miniconda3/envs/dgenies/lib/python3.12/site-packages/flask/__init__.py)

```

**Fix**
```
conda create -c conda-forge -c bioconda -n dgenies dgenies "flask<3"
conda activate dgenies
dgenies run
```

Reason: https://github.com/pallets/flask/pull/5223

**Comment by pbordron** [comment]
conda package was update, solving the issue
